import hot1 from "./images/hotel1.jpg";
import hot2 from "./images/hotel2.jpg";
import hot3 from "./images/hotel3.jpg";
import hot4 from "./images/hotel4.jpg";
import hot5 from "./images/hotel5.jpg";
import hot6 from "./images/hotel6.webp";
import hot7 from "./images/hotel7.jpg";
import hot8 from "./images/hotel8.jpg";
import hot9 from "./images/hotel9.jpg";
import hot10 from "./images/hotel10.jpg";
import hot11 from "./images/hotel11.jpg";
import hot12 from "./images/hotel12.jpg";
import hot13 from "./images/hotel13.jpg";
import hot14 from "./images/hotel14.jpg";
import hot15 from "./images/hotel15.jpg";
import hot16 from "./images/hotel16.jpg";
import hot17 from "./images/hotel17.webp";
import hot18 from "./images/hotel18.jpg";
import hot19 from "./images/hotel19.jpg";
import hot20 from "./images/hotel20.jpeg";
import hot21 from "./images/hotel21.jpg";
import hot22 from "./images/hotel22.jpg";
import hot23 from "./images/hotel23.jpg";
import hot24 from "./images/hotel24.jpg";
import hot25 from "./images/hotel25.jpg";

export default [
  {
    title: "Sunstar Hotel",
    star: 3,
    image: hot1,
    priceResident: "4000",
    priceNonResident: "65",
    location: "Nairobi",
    longitude: 36.823792,
    latitude: -1.28352,
    features: ["Swimming Pool", "Gym"],
  },
  {
    title: "Sentrim Boulevard Hotel",
    star: 3,
    image: hot2,
    priceResident: "4950",
    priceNonResident: "50",
    location: "Nairobi",
    longitude: 36.815361,
    latitude: -1.27787,
    features: [],
  },
  {
    title: "Mayhouse 680 Hotel",
    star: 3,
    image: hot3,
    priceResident: "4400",
    priceNonResident: "70",
    location: "Nairobi",
    longitude: 36.820564,
    latitude: -1.285157,
    features: [],
  },
  {
    title: "Nanchang Hotel",
    star: 4,
    image: hot4,
    priceResident: "5000",
    priceNonResident: "50",
    location: "Nairobi",
    longitude: 36.80394,
    latitude: -1.26379,
    features: [],
  },
  {
    title: "Hotel Emerald",
    star: 4,
    image: hot5,
    priceResident: "5000",
    priceNonResident: "50",
    location: "Nairobi",
    longitude: 36.81394,
    latitude: -1.26379,
    features: [],
  },
  {
    title: "LAICO Regency Hotel",
    star: 5,
    image: hot6,
    priceResident: "",
    priceNonResident: "",
    location: "Nairobi",
    longitude: 36.816792,
    latitude: -1.28192,
    features: [],
  },
  {
    title: "Eka Hotel Nairobi",
    star: 4,
    image: hot7,
    priceResident: "11830",
    priceNonResident: "130",
    location: "Nairobi",
    longitude: 36.837494,
    latitude: -1.320997,
    features: [],
  },
  {
    title: "La Maison Royale Hotel",
    star: 4,
    image: hot8,
    priceResident: "5600",
    priceNonResident: "60",
    location: "Nairobi",
    longitude: 36.820026,
    latitude: -1.285786,
    features: [],
  },
  {
    title: "Serena Hotel Nairobi",
    star: 5,
    image: hot9,
    priceResident: "12000",
    priceNonResident: "130",
    location: "Nairobi",
    longitude: 36.821949,
    latitude: -1.28707,
    features: [],
  },
  {
    title: "HillPark Hotel Nairobi",
    star: 4,
    image: hot10,
    priceResident: "7200",
    priceNonResident: "150",
    location: "Nairobi",
    longitude: 36.81839,
    latitude: -1.29627,
    features: [],
  },
  {
    title: "Nairobi Safari Club",
    star: 4,
    image: hot11,
    priceResident: "7600",
    priceNonResident: "80",
    location: "Nairobi",
    longitude: 36.817188,
    latitude: -1.28076,
    features: [],
  },
  {
    title: "Sarova Panafric",
    star: 5,
    image: hot12,
    priceResident: ["6700 Fri-Sun", "8500 Mon-Thur"],
    priceNonResident: ["70 Fri-Sun", "115 Mon-Thur"],
    location: "Nairobi",
    longitude: 36.81028,
    latitude: -1.28947,
    features: [],
  },
  {
    title: "Sankara Nairobi",
    star: 5,
    image: hot13,
    priceResident: "12000",
    priceNonResident: "125",
    location: "Nairobi",
    longitude: 36.816597,
    latitude: -1.283302,
    features: [],
  },
  {
    title: "Tribe Hotel",
    star: 5,
    image: hot14,
    priceResident: "",
    priceNonResident: "",
    location: "Nairobi",
    longitude: 36.903011,
    latitude: -1.18538,
    features: [],
  },
  {
    title: "Windsor Golf Hotel & Country Club",
    star: 5,
    image: hot15,
    priceResident: "11400",
    priceNonResident: "120",
    location: "Nairobi",
    longitude: 36.8512,
    latitude: -1.2101,
    features: [],
  },
  {
    title: "InterContinental Hotel",
    star: 5,
    image: hot16,
    priceResident: "9000",
    priceNonResident: "95",
    location: "Nairobi",
    longitude: 36.824211,
    latitude: -1.286,
    features: [],
  },
  {
    title: "Best Western Plus Meridian Nairobi",
    star: 4,
    image: hot17,
    priceResident: "8550",
    priceNonResident: "90",
    location: "Nairobi",
    longitude: 36.820999,
    latitude: -1.28131,
    features: [],
  },
  {
    title: "The Panari Hotel",
    star: 5,
    image: hot18,
    priceResident: "9000",
    priceNonResident: "90",
    location: "Nairobi",
    longitude: 36.823521,
    latitude: -1.298803,
    features: [],
  },
  {
    title: "Hilton Hotel",
    star: 5,
    image: hot19,
    priceResident: "",
    priceNonResident: "",
    location: "Nairobi",
    longitude: 36.82341,
    latitude: -1.28551,
    features: [],
  },
  {
    title: "Safari Park Hotel",
    star: 5,
    image: hot20,
    priceResident: "13650",
    priceNonResident: "150",
    location: "Nairobi",
    longitude: 36.857422,
    latitude: -1.29163,
    features: [],
  },
  {
    title: "Fairmont The Norfolk",
    star: 5,
    image: hot21,
    priceResident: "9910",
    priceNonResident: "180",
    location: "Nairobi",
    longitude: 36.815449,
    latitude: -1.277932,
    features: [],
  },
  {
    title: "Ole Sereni Hotel",
    star: 4,
    image: hot22,
    priceResident: "",
    priceNonResident: "",
    location: "Nairobi",
    longitude: 36.873348,
    latitude: -1.32945,
    features: [],
  },
  {
    title: "Boma Inn Hotel",
    star: 4,
    image: hot23,
    priceResident: "13300",
    priceNonResident: "140",
    location: "Nairobi",
    longitude: 36.833202,
    latitude: -1.32428,
    features: [],
  },
  {
    title: "Hemingways Hotel",
    star: 5,
    image: hot24,
    priceResident: "18000",
    priceNonResident: "190",
    location: "Nairobi",
    longitude: 36.705425,
    latitude: -1.342698,
    features: [],
  },
  {
    title: "Villa Rosa Kempinski",
    star: 5,
    image: hot25,
    priceResident: "14250",
    priceNonResident: "150",
    location: "Nairobi",
    longitude: 36.807621,
    latitude: -1.27079,
    features: [],
  },
];
